In [ ]:
import pandas as pd
import numpy as np
import math

In [2]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from utils import load_excel_file

In [3]:
data = load_excel_file("MC38-d1.xlsx", mode="all")
print(data.keys())

for sheet, tables in data.items():
    print(sheet, "tables:", len(tables))
    for t in tables:
        print(t.shape)

dict_keys(['plate1', 'plate2'])
plate1 tables: 1
(6, 10)
plate2 tables: 1
(4, 10)

In [5]:
from utils import find_all_tables_in_sheet


files = ["MC38-d1.xlsx"]
sheet_names = ["plate1", "plate2"]

all_tables = {}

for file in files:
    sheets = pd.read_excel(file, sheet_name=sheet_names, header=None)

    for sheet in sheet_names:
        tables_in_this_sheet = find_all_tables_in_sheet(sheets[sheet], anchor="<>")

        for i, t in enumerate(tables_in_this_sheet, start=1):
            key = f"{file} | {sheet} | table{i}"
            all_tables[key] = t

print("tables found:", len(all_tables))

for name, t in all_tables.items():
    print("\n=== ", name, " ===")
    display(t)

tables found: 2

===  MC38-d1.xlsx | plate1 | table1  ===

    2    3    4    5    6    7    8    9    10   11
B  114  336  206   96  266  135  118  197  114  188
C  118  113  180  181  209  176   98  252  367   95
D  226  457  507  375  249  391  323  205  393  481
E  247  320  249  240  442  311  435  311  340  420
F    3   -4    7    0   -3    0   -1    9    2    1
G   77   91   95    2   -1   -1    2    0   -4    7

===  MC38-d1.xlsx | plate2 | table1  ===

    2    3    4    5    6    7    8    9    10   11
B  317  263  485  298  236  406  456  325  388  370
C  295  477  373  326  342  243  186  188  227  212
D  146  359  228  194  288  281  396  486  141  120
E  337  136  284  146  181  193  397  200  195  365